RealTimeCollaborativeWhiteboard/Controllers/ViewNotesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealTimeCollaborativeWhiteboard.Data;
using RealTimeCollaborativeWhiteboard.Models;
using System.Composition;
using System.Security.Claims;

namespace RealTimeCollaborativeWhiteboard.Controllers
{
    public class ViewNotesController : Controller
    {

        private readonly ApplicationDbContext _dbContext;

        public ViewNotesController( ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        [Authorize]
        public ActionResult Index()
        {
            var notes = _dbContext.Notes.ToList();
            return View(notes);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                var note = await _dbContext.Notes.FirstOrDefaultAsync(p => p.NotesId == id);
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                if (note.CurrUserID == userId)
                {
                    if (note != null)
                    {
                        _dbContext.Notes.Remove(note);
                        await _dbContext.SaveChangesAsync();
                    }
                }
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Notes note = await _dbContext.Notes.FindAsync(id);
            if (note == null)
            {
                return RedirectToAction("Index");
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (note.CurrUserID != userId) {
                return RedirectToAction("Index");
            }

            return View(note);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(int id, Notes updateNote)
        {
            var note = await _dbContext.Notes.FirstOrDefaultAsync(p => p.NotesId == id);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (note != null)
            {
                if(note.CurrUserID == userId) {
                    if (updateNote.Title != null && updateNote.Content != null)
                    {
                        note.Title = updateNote.Title;
                        note.Content = updateNote.Content;
                    }
                }
                await _dbContext.SaveChangesAsync();
            }
            return RedirectToAction("Edit");
        }
    }
}

RealTimeCollaborativeWhiteboard/Views/ViewNotes/Edit.cshtml
@model RealTimeCollaborativeWhiteboard.Models.Notes

@{
    ViewBag.Title = "Edit Note";
}

<h2>Edit Note</h2>

@using (Html.BeginForm("Edit", "ViewNotes", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.HiddenFor(model => model.NotesId)

        <label class="control-label">Title</label>
        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })

        <label class="control-label">Content</label>
        @Html.TextAreaFor(model => model.Content, new { @class = "form-control" })

        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
}

@Html.ActionLink("Back to List", "Index")

RealTimeCollaborativeWhiteboard/Views/ViewNotes/Index.cshtml
@model IEnumerable<RealTimeCollaborativeWhiteboard.Models.Notes>
@{
    ViewBag.Title = "Test Desk";
}

<h1 class="text-light">Notes page</h1>
<table class="table text-light">
    <thead>
        <tr>
            <th>Name</th>
            <th>Content</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Title</td>
                <td>@item.Content</td>
                <td>
                    <form asp-controller="ViewNotes" asp-action="Delete" method="post" asp-route-id="@item.NotesId">
                        <input type="submit" value="Удалить" />
                    </form>
                </td>
                <td>
                    <form asp-controller="ViewNotes" asp-action="Edit" method="post" asp-route-id="@item.NotesId">
                        <input type="submit" value="Edit" />
                    </form>
                </td>
            </tr>
        }
    </tbody>

</table>