RealTimeCollaborativeWhiteboard/Controllers/UploadImagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealTimeCollaborativeWhiteboard.Data;
using RealTimeCollaborativeWhiteboard.Models;
using RealTimeCollaborativeWhiteboard.Services;
using System.Security.Claims;

namespace RealTimeCollaborativeWhiteboard.Controllers
{
    public class UploadImagesController : Controller, IFileStorage
    {
        private readonly ApplicationDbContext _dbContext;

        public UploadImagesController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var image = _dbContext.Images.ToList();
            return View(image);
        }

        [HttpPost]
        [Authorize]
        [RequestFormLimits(MultipartBodyLengthLimit = 104857600)]
        public async Task<IActionResult> SaveFile(IFormFile photoFile)
        {
            if (photoFile != null && photoFile.Length > 0)
            {
                var uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "Data", "Photos");
                var uniqueFileName = Path.GetRandomFileName() + Path.GetExtension(photoFile.FileName);
                var filePath = Path.Combine(uploadsFolder, uniqueFileName);

                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await photoFile.CopyToAsync(fileStream);
                }

                var file = new Image
                {
                    UrlImage = uniqueFileName,
                    CurrUserID = userId
                };

                _dbContext.Images.Add(file);
                await _dbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult GetFile(string fileName)
        {
            var filePath = Path.Combine("Data", "Photos", fileName);
            var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
            return File(fileStream, "image/jpeg");
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> DeleteFile(int id)
        {
            var image = await _dbContext.Images.FirstOrDefaultAsync(f => f.ImageId == id);
            if (image != null)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                if (image.CurrUserID == userId)
                {
                    if (!string.IsNullOrEmpty(image.UrlImage))
                    {
                        var filePath = Path.Combine("Data", "Photos", image.UrlImage);

                        if (System.IO.File.Exists(filePath))
                        {
                            System.IO.File.Delete(filePath);
                        }
                    }
                }
                _dbContext.Images.Remove(image);
                await _dbContext.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

RealTimeCollaborativeWhiteboard/Views/UploadImages/Index.cshtml
@model IEnumerable<RealTimeCollaborativeWhiteboard.Models.Image>

@{
    ViewData["Title"] = "Files Gallery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4 card-container p-4">
    <div class="block text-light">
        <h1>@ViewData["Title"]</h1>

        <!-- Button to trigger modal -->
		<button type="button" class="custom-btn btn main-btn w-25" id="uploadNewPhotoBtn"><span>Upload New Photo</span></button>
    </div>

    <div class="block text-light mt-3">
        <!-- Image gallery -->
        <h2>Image Gallery</h2>
        <div class="row">
            @if (Model != null)
            {
                @foreach (var image in Model)
                {
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            <img src="@Url.Action("GetFile", "UploadImages", new { fileName = image.UrlImage })" class="card-img-top" alt="Photo" data-toggle="modal" data-target="#exampleModal" />
                            <div class="card-body">
                                <form method="post" asp-action="DeleteFile" asp-controller="UploadImages">
                                    <input type="hidden" name="id" value="@image.ImageId" />
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <p class="container">No images found</p>
            }
        </div>
    </div>
</div>
<!-- Modal for Upload new photo form -->
<div class="modal fade" id="uploadPhotoModal" tabindex="-1" role="dialog" aria-labelledby="uploadPhotoModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="uploadPhotoModalLabel">Upload New Photo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" asp-action="SaveFile" asp-controller="UploadImages" enctype="multipart/form-data">
                    <div class="mb-3">
                        <label for="photoFile" class="form-label">Select Photo:</label>
                        <input type="file" class="form-control" id="photoFile" name="photoFile" accept="image/*" />
                    </div>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal for displaying images -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Image</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img id="modalImage" src="" class="img-fluid" alt="Image">
                <a id="downloadButton" class="btn btn-secondary mt-2" download="image.jpg">Download</a>
            </div>
        </div>
    </div>
</div>

RealTimeCollaborativeWhiteboard/Views/UploadImages/UploadImage.cshtml
@model RealTimeCollaborativeWhiteboard.Models.Image

@{
    ViewBag.Title = "Test Files";
}

<h2>Test Files</h2>

@using (Html.BeginForm("SaveFile", "UploadImages", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <label for="photoFile">Select Photo:</label>
        <input type="file" name="photoFile" id="photoFile" accept="image/*" />
    </div>
    <button type="submit">Save Photo</button>
}