RealTimeCollaborativeWhiteboard/Controllers/ViewDeskController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealTimeCollaborativeWhiteboard.Data;
using RealTimeCollaborativeWhiteboard.Models;

namespace RealTimeCollaborativeWhiteboard.Controllers
{
    public class ViewDeskController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly ApplicationDbContext _dbContext;

        public ViewDeskController(IWebHostEnvironment environment, ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
            _environment = environment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var desks = _dbContext.Desks.ToList(); 
            return View(desks);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePhoto(int id)
        {
            var image = await _dbContext.Desks.FirstOrDefaultAsync(f => f.DeskID == id);
            if (image != null)
            {
                if (!string.IsNullOrEmpty(image.UrlPhoto))
                {
                    var filePath = Path.Combine(_environment.WebRootPath, "Photos", image.UrlPhoto);
                    if (System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                    }
                }

                _dbContext.Desks.Remove(image);
                await _dbContext.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

RealTimeCollaborativeWhiteboard/Views/ViewDesk/Index.cshtml
@model IEnumerable<RealTimeCollaborativeWhiteboard.Models.Desk>
@{
    ViewBag.Title = "Test Desk";
}

<h1>Image Gallery</h1>
<div>
    @foreach (var desk in Model)
    {
        <img class="fixed-size-image" src="~/Photos/@desk.UrlPhoto" data-toggle="modal" data-target="#exampleModal" />
        <form method="post" asp-action="DeletePhoto" asp-controller="ViewDesk">
            <input type="hidden" name="id" value="@desk.DeskID" />
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    }
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Зображення</h5>
                <button type="button" class="close d-flex justify-content-center align-items-center" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&#10005;</span>
                </button>
            </div>
            <div class="modal-body">
                <img id="modalImage" src="" class="img-fluid fixed-size-image__modal" alt="Зображення">
                <a id="downloadButton" class="btn btn-secondary mt-2" download="image.jpg">Download</a>
            </div>
        </div>
    </div>
</div>